import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["600", "700"], // Defina os pesos que deseja usar
  style: ["normal", "italic"], // Se precisar de estilos específicos
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <GoogleOneTap />
        <body className={poppins.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
